/* copy.jsx — ES/EN content bundle. Centralised so the language toggle works
   across the whole page and the user can edit copy in one place. */

const COPY = {
  es: {
    nav: {
      links: [
        { id: 'servicios', label: 'Servicios' },
        { id: 'planes',    label: 'Planes' },
        { id: 'proceso',   label: 'Proceso' },
        { id: 'casos',     label: 'Casos' },
        { id: 'contacto',  label: 'Contacto' },
      ],
      status: 'Aceptando 2 proyectos',
      cta: 'Empezar proyecto',
      ctaGhost: 'Ver casos',
    },
    hero: {
      eyebrow: 'Software a medida · Jujuy · Salta · Tucumán',
      titleA: 'Software',
      titleB: 'que pone',
      titleC: 'al norte',
      titleD: 'en línea.',
      lead:
        'Construimos sistemas que las pymes del norte argentino necesitan de verdad: ecommerce, turneros, gestión de gimnasios y restaurantes, e-ticketing. Sin frameworks de moda, sin promesas raras.',
      footMeta: 'San Salvador de Jujuy · GMT‑3',
      footStatus: 'Operacional',
      cornerLine1: '/ CN-SOL-2025',
      cornerLine2: '24.1854°S, 65.2995°W',
    },
    marquee: [
      'React · Next.js', 'Node.js · TypeScript', 'PostgreSQL · Redis',
      'Mercado Pago · Stripe · MODO', 'AFIP · Factura electrónica',
      'WhatsApp Business API', 'Tailwind · Astro', 'Supabase · Prisma',
      'Docker · Cloudflare', 'Resend · Twilio',
    ],
    services: {
      eyebrow: '01 — Productos',
      num: 'Capítulo 01',
      title: 'Seis sistemas que entendemos',
      titleEm: 'al dedillo',
      lead:
        'Cada uno con más de un cliente productivo. No te vendemos un prototipo: te entregamos algo que ya rodó.',
      items: [
        {
          n: '/ 01',
          title: 'Ecommerce',
          titleEm: 'a medida',
          body:
            'Tienda online con catálogo, carrito, pasarela (Mercado Pago, MODO, Stripe), facturación electrónica AFIP y panel propio. Sin Shopify atándote al fee.',
          tags: ['Mercado Pago', 'AFIP', 'Catálogo', 'Multi-sucursal'],
          mock: 'shop',
          stats: [
            { n: '0%', l: 'comisión por venta' },
            { n: '<2s', l: 'TTFB en mobile' },
          ],
        },
        {
          n: '/ 02',
          title: 'Gestión',
          titleEm: 'gastronómica',
          body:
            'Comanda en cocina, mesas, takeaway, delivery propio, control de stock, arqueo. Tablet en el salón, KDS en la parrilla.',
          tags: ['KDS', 'POS', 'Delivery', 'Stock', 'Caja'],
          mock: 'orders',
          stats: [
            { n: '12s', l: 'ticket promedio' },
            { n: '0', l: 'errores de comanda' },
          ],
        },
        {
          n: '/ 03',
          title: 'Gimnasios',
          titleEm: '& wellness',
          body:
            'Socios, cuotas con débito automático, control de acceso por QR, clases con cupo, reportes de retención.',
          tags: ['Débito auto.', 'QR access', 'Clases', 'Retención'],
          mock: 'gym',
        },
        {
          n: '/ 04',
          title: 'E-ticketing',
          body:
            'Venta de entradas con QR validable offline, sectores, butacas, controles en puerta y reportes en vivo durante el evento.',
          tags: ['QR offline', 'Mapeo butacas', 'Lectores'],
          mock: 'ticket',
        },
        {
          n: '/ 05',
          title: 'Turneros',
          body:
            'Para clínicas, oficinas públicas, bancos. Pantalla TV, dispensador, llamado por voz, métricas de espera y atención.',
          tags: ['Multi-box', 'TTS', 'Métricas'],
          mock: 'queue',
        },
        {
          n: '/ 06',
          title: 'Landing pages',
          titleEm: 'profesionales',
          body:
            'Para abogados, contadores, médicos, arquitectos. Diseño propio, formularios serios, SEO local y carga en menos de un segundo.',
          tags: ['SEO local', 'A11y', '<1s'],
          mock: 'chart',
        },
      ],
    },
    process: {
      eyebrow: '02 — Cómo trabajamos',
      num: 'Capítulo 02',
      title: 'Cuatro semanas',
      titleEm: 'a producción',
      lead:
        'Ni waterfall ni scrum-de-cartón. Iteramos con vos cada semana, mostramos avances reales y entregamos un sistema andando, no un PDF.',
      steps: [
        { t: 'Descubrimiento',  d: 'Te visitamos (sí, en serio). Mapeamos flujos actuales, escuchamos al equipo, definimos el alcance mínimo viable.', dur: 'Semana 01' },
        { t: 'Diseño',          d: 'Wireframes y prototipos navegables. Validamos con los usuarios reales antes de tocar una línea de código.', dur: 'Semana 02' },
        { t: 'Construcción',    d: 'Desarrollo en sprints de 5 días con demos los viernes. Vos ves el progreso, opinás, ajustamos.', dur: 'Semana 03–04' },
        { t: 'Puesta en marcha',d: 'Migración de datos, capacitación al equipo, semana de hypercare. Después: soporte mensual opcional.', dur: 'Semana 05' },
      ],
    },
    work: {
      eyebrow: '03 — Casos',
      num: 'Capítulo 03',
      title: 'Lo último',
      titleEm: 'que hicimos',
      lead: 'Una muestra. Hay más bajo NDA; pedinos un demo en privado.',
      items: [
        { cat: 'Ecommerce',   t: 'La Posta — Vinos del Valle',     m: 'Tienda + suscripción mensual de vinos. 480 clientes activos.' , kind: 'shop'},
        { cat: 'Gastronomía', t: 'Almacén del Sur — 3 sucursales', m: 'Comandas, stock y delivery unificado. Tiempo de salida ↓ 38%.', kind: 'orders' },
        { cat: 'Gimnasios',   t: 'Club Atlético San Pedro',         m: '1.200 socios. Débito automático, control QR, clases con cupo.', kind: 'gym' },
        { cat: 'E-ticketing', t: 'Festival Pachamama 2025',         m: '14.000 entradas vendidas. Validación QR sin internet en puerta.', kind: 'ticket' },
      ],
    },
    stack: {
      eyebrow: '04 — Stack',
      num: 'Capítulo 04',
      title: 'Lo que usamos,',
      titleEm: 'sin parecer feria',
      lead: 'Apostamos a herramientas estables, no a la moda del mes. Lo que está acá lleva años en producción nuestra.',
      items: [
        { n: 'TypeScript', c: 'Lenguaje' },
        { n: 'React',      c: 'Frontend' },
        { n: 'Next.js',    c: 'Framework' },
        { n: 'Node.js',    c: 'Backend' },
        { n: 'PostgreSQL', c: 'Base de datos' },
        { n: 'Redis',      c: 'Cache / colas' },
        { n: 'Prisma',     c: 'ORM' },
        { n: 'Tailwind',   c: 'Estilos' },
        { n: 'Mercado Pago', c: 'Pagos AR' },
        { n: 'Stripe',     c: 'Pagos USD' },
        { n: 'AFIP WS',    c: 'Facturación' },
        { n: 'Cloudflare', c: 'Infra / CDN' },
      ],
    },
    quotes: {
      eyebrow: '05 — Lo que dicen',
      num: 'Capítulo 05',
      title: 'No te creas',
      titleEm: 'lo que decimos',
      lead: 'Creele al que ya lo está usando todos los días.',
      items: [
        {
          q: 'Pasamos de Excel a un sistema serio en cinco semanas. Los socios renuevan solos por débito automático y yo dejé de correr atrás de cobranzas.',
          who: 'Mariano Quispe', role: 'Director, Club San Pedro', av: 'MQ',
        },
        {
          q: 'Lo que más valoré: vinieron al local, entendieron cómo trabajábamos y armaron algo que mi mozo entiende sin capacitación.',
          who: 'Laura Mamaní', role: 'Dueña, Almacén del Sur', av: 'LM',
        },
        {
          q: 'Validamos 14.000 entradas en una noche sin internet en el predio. Algo que con la solución anterior era impensable.',
          who: 'Diego Fernández', role: 'Productor, Festival Pachamama', av: 'DF',
        },
      ],
    },
    metrics: {
      items: [
        { n: '37', u: '', l: 'Proyectos entregados' },
        { n: '<5', u: 'sem', l: 'Tiempo a producción' },
        { n: '99.9', u: '%', l: 'Uptime últimos 12m' },
        { n: '4', u: '', l: 'Provincias activas' },
      ],
    },
    plans: {
      eyebrow: '· Planes',
      num: 'Capítulo 03',
      title: 'Elegí tu plan,',
      titleEm: 'crecé sin techo',
      lead: 'Cada uno de nuestros sistemas viene en tres tamaños. Empezás con lo que necesitás hoy, escalás cuando hace falta. Sin contratos eternos: mes a mes, cancelás cuando quieras.',
      payHd: 'Tus clientes pagan con',
      payFoot: 'Activamos cada método sin cargo adicional. Comisiones según el proveedor.',
      payMethods: [
        'Mercado Pago', 'MODO', 'Visa', 'Mastercard', 'American Express', 'Naranja X', 'Cabal', 'Transferencia (CBU/CVU)', 'Efectivo (Pago Fácil/Rapipago)',
      ],
      tabs: [
        { id: 'ecommerce', n: '01', name: 'Ecommerce',     intro: 'Vendé online sin pagarle un peaje a Shopify.',         lead: 'Tienda propia con catálogo, carrito, pasarela de pago integrada y facturación electrónica AFIP. Es tu plataforma, sin comisiones por venta nuestras.' },
        { id: 'ticket',    n: '02', name: 'E-ticketera',   intro: 'Vendé entradas y validá QR offline en la puerta.',     lead: 'Para festivales, teatros, espectáculos y eventos corporativos. Cobrá con Mercado Pago, sentás butacas y entrá al evento sin internet.' },
        { id: 'gastro',    n: '03', name: 'Gastronomía',   intro: 'Mozo, cocina, delivery y caja, en un mismo sistema.',  lead: 'POS para mesas y mostrador, KDS en cocina, delivery propio, stock por insumo y arqueo de caja. Tablet en el salón, listo.' },
        { id: 'gym',       n: '04', name: 'Gimnasios',     intro: 'Socios, cuotas y acceso QR sin volverte loco.',         lead: 'Débito automático, control de acceso por QR, clases con cupo, métricas de retención. Para gimnasios, estudios, pilates, crossfit.' },
        { id: 'queue',     n: '05', name: 'Turneros',      intro: 'Llamado por voz, pantalla TV y métricas en vivo.',     lead: 'Para clínicas, oficinas públicas, bancos y consultorios. Multi-box, llamado por TTS, métricas de espera y atención.' },
        { id: 'landing',   n: '06', name: 'Landing pro',   intro: 'Tu cara online — sin templates de Wix.',                lead: 'Sitio profesional para abogados, contadores, médicos, arquitectos. Diseño a medida, formularios serios, SEO local.' },
      ],
      monthly: '/mes',
      setup: 'Setup',
      featured: 'Más elegido',
      footer: [
        { h: 'Métodos de pago aceptados',    p: 'Mercado Pago, MODO, todas las tarjetas argentinas (Visa, Mastercard, Amex, Naranja, Cabal) y transferencia CBU/CVU. Activamos lo que tu negocio necesite.' },
        { h: 'Tu data, tu código',           p: 'Repositorio, hosting y credenciales a tu nombre. Si dejás de trabajar con nosotros, te entregamos las llaves y listo. Sin lock-in.' },
        { h: 'Sin sorpresas en la factura',  p: 'Precios en pesos argentinos. Sin comisión por venta, sin cargos por usuario, sin tarifas ocultas. Soporte incluido en todos los planes.' },
      ],
      software: {
        ecommerce: [
          { tier: 'Starter', tag: 'STR', sub: 'Para empezar a vender ya', price: 89000, setup: 450000, feats: [
            ['Hasta', '100 productos'], ['', '1 sucursal · 1 admin'], ['', 'Catálogo + carrito + checkout'],
            ['Pagos:', 'Mercado Pago + transferencia'], ['', 'Facturación AFIP (Mono/RI)'],
            ['', 'Dominio + SSL + hosting incluido'], ['Soporte', 'por email · 48 h'],
          ], muted: ['Sin suscripciones recurrentes', 'Sin app móvil propia'] },
          { tier: 'Grow', tag: 'GRW', sub: 'Para vender en serio', price: 159000, setup: 850000, featured: true, feats: [
            ['Hasta', '1.000 productos'], ['', '3 sucursales · 5 usuarios'], ['', 'Todo lo de Starter, más:'],
            ['Pagos:', 'MP, MODO, Stripe, tarjetas'], ['', 'Suscripciones / pedidos recurrentes'],
            ['', 'Cupones, descuentos, gift cards'], ['', 'Integración con Andreani / OCA / Correo'],
            ['Soporte', 'WhatsApp · 24 h'],
          ], muted: ['Sin ERP / SAP integración'] },
          { tier: 'Pro', tag: 'PRO', sub: 'Operaciones a escala', price: 290000, setup: 'a medida', feats: [
            ['', 'Productos ilimitados'], ['', 'Multi-sucursal · usuarios ilimitados'], ['', 'Todo lo de Grow, más:'],
            ['', 'API custom + integraciones'], ['', 'ERP / SAP / Tango / Bejerman'],
            ['', 'Multi-moneda · multi-idioma'], ['', 'B2B portal + listas de precio'],
            ['', 'SLA 99.9% · ambiente staging'], ['Soporte', 'dedicado · 4 h'],
          ] },
        ],
        ticket: [
          { tier: 'Starter', tag: 'STR', sub: 'Tu primer evento online', price: 'comisión', priceNum: '4,5%', priceSuffix: 'por ticket vendido', setup: 0, feats: [
            ['Hasta', '500 entradas por evento'], ['', '1 productor · 1 evento simultáneo'], ['', 'Tipos de entrada (general, vip, early)'],
            ['Pagos:', 'Mercado Pago + transferencia'], ['', 'QR validable offline desde celular'],
            ['', 'Reporte de ventas en vivo'], ['Soporte', 'por email'],
          ], muted: ['Sin mapeo de butacas', 'Sin scanners físicos'] },
          { tier: 'Grow', tag: 'GRW', sub: 'Festivales y eventos medianos', price: 'comisión', priceNum: '3,5%', priceSuffix: 'por ticket vendido', setup: 280000, featured: true, feats: [
            ['Hasta', '5.000 entradas por evento'], ['', 'Múltiples eventos simultáneos'], ['', 'Todo lo de Starter, más:'],
            ['', 'Mapeo de butacas / sectores'], ['Pagos:', 'MP + MODO + tarjetas + débito'],
            ['', 'Hasta 4 puntos de validación'], ['', 'Scanners físicos opcionales'],
            ['', 'WhatsApp con QR automático'], ['Soporte', 'WhatsApp · 24 h'],
          ] },
          { tier: 'Pro', tag: 'PRO', sub: 'Productoras y giras grandes', price: 'comisión', priceNum: '2,5%', priceSuffix: 'o cuota fija mensual', setup: 'a medida', feats: [
            ['', 'Entradas ilimitadas'], ['', 'Multi-evento · multi-organización'], ['', 'Todo lo de Grow, más:'],
            ['', 'White-label con tu marca'], ['', 'API + integración con CRMs'],
            ['', 'Hasta 20 puntos de validación'], ['', 'Reventas controladas + transferencias'],
            ['', 'SLA 99.9% durante el evento'], ['Soporte', '24/7 en evento'],
          ] },
        ],
        gastro: [
          { tier: 'Starter', tag: 'STR', sub: 'Un solo local', price: 69000, setup: 380000, feats: [
            ['', '1 local · 5 dispositivos'], ['', 'POS para mesas y mostrador'], ['', 'KDS básico en cocina'],
            ['', 'Stock por producto'], ['Pagos:', 'MP, tarjetas, efectivo'],
            ['', 'Arqueo de caja'], ['Soporte', 'email · 48 h'],
          ], muted: ['Sin delivery propio', 'Sin programa de fidelización'] },
          { tier: 'Grow', tag: 'GRW', sub: 'Hasta 3 locales', price: 129000, setup: 680000, featured: true, feats: [
            ['', '3 locales · 15 dispositivos'], ['', 'Todo lo de Starter, más:'], ['', 'Delivery propio + repartidores'],
            ['', 'Stock por insumo (recetas)'], ['', 'Programa de fidelización'],
            ['Pagos:', 'MP, MODO, tarjetas, QR'], ['', 'Integración con Rappi / PedidosYa'],
            ['Soporte', 'WhatsApp · 24 h'],
          ] },
          { tier: 'Pro', tag: 'PRO', sub: 'Cadenas y franquicias', price: 240000, setup: 'a medida', feats: [
            ['', 'Locales ilimitados'], ['', 'Todo lo de Grow, más:'], ['', 'Multi-marca / multi-razón social'],
            ['', 'BI: ventas, mermas, rentabilidad'], ['', 'API para integrar tu ERP'],
            ['', 'App móvil del cliente (white-label)'], ['', 'SLA 99.9% en horario operativo'],
            ['Soporte', 'dedicado · 4 h'],
          ] },
        ],
        gym: [
          { tier: 'Starter', tag: 'STR', sub: 'Gym de barrio / estudio', price: 59000, setup: 320000, feats: [
            ['Hasta', '300 socios activos'], ['', '1 sede'], ['', 'Cuotas + recordatorios automáticos'],
            ['Pagos:', 'MP, transferencia, efectivo'], ['', 'Control de acceso manual'],
            ['', 'Carnet digital con QR'], ['Soporte', 'email · 48 h'],
          ], muted: ['Sin débito automático', 'Sin clases con cupo'] },
          { tier: 'Grow', tag: 'GRW', sub: 'Gimnasio establecido', price: 119000, setup: 580000, featured: true, feats: [
            ['Hasta', '1.500 socios activos'], ['', 'Hasta 3 sedes'], ['', 'Todo lo de Starter, más:'],
            ['', 'Débito automático MP / tarjeta'], ['', 'Control de acceso por QR (molinete)'],
            ['', 'Clases con cupo + lista de espera'], ['', 'Reportes de retención + churn'],
            ['Soporte', 'WhatsApp · 24 h'],
          ] },
          { tier: 'Pro', tag: 'PRO', sub: 'Cadena multi-sede', price: 220000, setup: 'a medida', feats: [
            ['', 'Socios ilimitados'], ['', 'Sedes ilimitadas'], ['', 'Todo lo de Grow, más:'],
            ['', 'App móvil propia (iOS + Android)'], ['', 'Reservas, evaluaciones, planes de entrenamiento'],
            ['', 'Integración con balanzas / cardio'], ['', 'BI multi-sede'],
            ['Soporte', 'dedicado · 4 h'],
          ] },
        ],
        queue: [
          { tier: 'Starter', tag: 'STR', sub: 'Una sede chica', price: 49000, setup: 240000, feats: [
            ['', '1 sede · 3 boxes'], ['', 'Pantalla TV + dispensador'], ['', 'Llamado por audio'],
            ['', 'Métricas básicas de espera'], ['', 'Tickets impresos o digitales'],
            ['Soporte', 'email · 48 h'],
          ], muted: ['Sin TTS por voz', 'Sin reservas previas'] },
          { tier: 'Grow', tag: 'GRW', sub: 'Múltiples sedes', price: 99000, setup: 480000, featured: true, feats: [
            ['', 'Hasta 5 sedes · 10 boxes c/u'], ['', 'Todo lo de Starter, más:'], ['', 'TTS: llamado por voz por box'],
            ['', 'Múltiples colas / prioridades'], ['', 'Reservas previas online + WhatsApp'],
            ['', 'Métricas detalladas + dashboards'], ['Soporte', 'WhatsApp · 24 h'],
          ] },
          { tier: 'Pro', tag: 'PRO', sub: 'Bancos / oficinas públicas', price: 180000, setup: 'a medida', feats: [
            ['', 'Sedes ilimitadas · boxes ilimitados'], ['', 'Todo lo de Grow, más:'], ['', 'API + integración con tu sistema'],
            ['', 'Encuestas post-atención'], ['', 'Reglas de derivación complejas'],
            ['', 'SLA 99.9% en horario hábil'], ['Soporte', 'dedicado · 4 h'],
          ] },
        ],
        landing: [
          { tier: 'Starter', tag: 'STR', sub: 'Un sitio bien hecho', price: 19000, priceLead: 380000, setup: 0, feats: [
            ['Único', '$ 380.000 + $ 19.000/mes hosting'], ['', '1 página · diseño a medida'], ['', 'Hasta 4 secciones'],
            ['', 'Formulario de contacto · email'], ['', 'SEO local + Google Business'],
            ['', 'Dominio + SSL + hosting incluido'], ['Soporte', 'email · 1 cambio/mes'],
          ], muted: ['Sin blog / CMS', 'Sin multi-idioma'] },
          { tier: 'Grow', tag: 'GRW', sub: 'Tu firma o consultorio', price: 29000, priceLead: 680000, setup: 0, featured: true, feats: [
            ['Único', '$ 680.000 + $ 29.000/mes hosting'], ['', '5 páginas · diseño a medida'], ['', 'Todo lo de Starter, más:'],
            ['', 'Blog con CMS para que edites vos'], ['', 'Agenda / turnos integrada'],
            ['Pagos:', 'MP para señas / consultas'], ['', 'Multi-formulario + autorespuestas'],
            ['Soporte', '4 cambios/mes'],
          ] },
          { tier: 'Pro', tag: 'PRO', sub: 'Estudio o agencia grande', price: 49000, priceLead: 1200000, setup: 0, feats: [
            ['Único', '$ 1.200.000 + $ 49.000/mes hosting'], ['', 'Páginas ilimitadas'], ['', 'Todo lo de Grow, más:'],
            ['', 'Multi-idioma (ES/EN/PT)'], ['', 'Integración con tu CRM / HubSpot'],
            ['', 'A/B testing + analytics'], ['', 'Performance < 1 s · Lighthouse 95+'],
            ['Soporte', 'cambios ilimitados'],
          ] },
        ],
      },
      cta: 'Empezar con',
      ctaPro: 'Hablemos',
      currency: 'AR$',
    },
    faq: {
      eyebrow: '06 — Preguntas',
      num: 'Capítulo 06',
      title: 'Lo que siempre',
      titleEm: 'nos preguntan',
      items: [
        { q: '¿Cuánto sale un proyecto?',
          a: 'Depende del alcance, pero la mayoría arranca entre AR$ 3.5M y AR$ 12M. Te damos un presupuesto cerrado después de la fase de descubrimiento, sin cláusulas raras.' },
        { q: '¿Trabajan solo en el norte?',
          a: 'No, pero conocemos bien la realidad de las pymes del NOA. Tenemos clientes en CABA, Mendoza, Córdoba y Asunción. Las reuniones presenciales valen para Jujuy/Salta/Tucumán.' },
        { q: '¿De quién es el código?',
          a: 'Tuyo. Repositorio, credenciales, hosting: todo a tu nombre. Si un día querés cambiar de proveedor, te entregamos las llaves y listo.' },
        { q: '¿Hacen mantenimiento después?',
          a: 'Sí, plan mensual opcional desde AR$ 280k con SLA. Si preferís contratar a otro o tu equipo interno, te dejamos documentación y un par de sesiones de transferencia.' },
        { q: '¿Integran con AFIP y Mercado Pago?',
          a: 'Sí, son integraciones que ya tenemos hechas y probadas. Facturación electrónica (FCE, FCE-MiPyME), QR, descuentos, débito automático, todo el menú.' },
        { q: '¿Y si necesito algo que no está en la lista?',
          a: 'Lo más probable es que también lo hayamos hecho. Escribinos contando qué necesitás; si no es lo nuestro te recomendamos a alguien que sí.' },
      ],
    },
    contact: {
      eyebrow: '07 — Trabajemos juntos',
      num: 'Capítulo 07',
      title: 'Contanos',
      titleEm: 'tu proyecto',
      lead: 'Respondemos en menos de 24 horas hábiles. Sin embudos de venta, sin agencias de discovery.',
      form: {
        name: 'Nombre',
        company: 'Empresa / Proyecto',
        email: 'Email',
        type: 'Tipo de proyecto',
        types: ['Ecommerce', 'Gastronomía', 'Gimnasios', 'E-ticketing', 'Turneros', 'Landing profesional', 'Otro / consultar'],
        budget: 'Presupuesto estimado',
        budgets: ['< AR$ 3M', 'AR$ 3–8M', 'AR$ 8–15M', '> AR$ 15M', 'Aún no lo sé'],
        msg: 'Contanos qué necesitás',
        send: 'Enviar consulta',
      },
      successTitle: 'Listo. Recibimos tu consulta.',
      successBody: 'Te respondemos en menos de 24 horas hábiles desde hola@codigonorte.com.ar. Si es urgente, escribinos por WhatsApp.',
      aside: [
        { h: 'Por email', body: <>Escribinos a <a href="mailto:hola@codigonorte.com.ar">hola@codigonorte.com.ar</a></> },
        { h: 'Por WhatsApp', body: <>De 9 a 19 (GMT‑3). <a href="#">+54 388 415 0000</a></> },
        { h: 'En persona', body: <>Belgrano 1024, San Salvador de Jujuy. Pedinos café antes de venir.</> },
      ],
    },
    footer: {
      cols: [
        { h: 'Productos', links: ['Ecommerce', 'Gastronomía', 'Gimnasios', 'E-ticketing', 'Turneros', 'Landings'] },
        { h: 'Empresa', links: ['Sobre nosotros', 'Casos', 'Blog', 'Privacidad'] },
        { h: 'Contacto', links: ['hola@codigonorte.com.ar', '+54 388 415 0000', 'WhatsApp', 'Instagram'] },
      ],
      base: '© 2025 Código Norte Soluciones — San Salvador de Jujuy, Argentina',
      baseRight: 'Última actualización · v3.2.1',
      wordmark: 'codigo norte.',
    },
  },

  en: {
    nav: {
      links: [
        { id: 'servicios', label: 'Services' },
        { id: 'planes',    label: 'Plans' },
        { id: 'proceso',   label: 'Process' },
        { id: 'casos',     label: 'Work' },
        { id: 'contacto',  label: 'Contact' },
      ],
      status: 'Booking 2 projects',
      cta: 'Start a project',
      ctaGhost: 'See work',
    },
    hero: {
      eyebrow: 'Custom software · Jujuy · Salta · Tucumán',
      titleA: 'Software',
      titleB: 'that puts',
      titleC: 'the north',
      titleD: 'online.',
      lead:
        'We build systems that small businesses in northern Argentina actually need: ecommerce, queuing, gym and restaurant management, e-ticketing. No fashion frameworks, no weird promises.',
      footMeta: 'San Salvador de Jujuy · GMT‑3',
      footStatus: 'Operational',
      cornerLine1: '/ CN-SOL-2025',
      cornerLine2: '24.1854°S, 65.2995°W',
    },
    marquee: [
      'React · Next.js', 'Node.js · TypeScript', 'PostgreSQL · Redis',
      'Mercado Pago · Stripe · MODO', 'AFIP e-invoicing',
      'WhatsApp Business API', 'Tailwind · Astro', 'Supabase · Prisma',
      'Docker · Cloudflare', 'Resend · Twilio',
    ],
    services: {
      eyebrow: '01 — Products',
      num: 'Chapter 01',
      title: 'Six systems we know',
      titleEm: 'inside out',
      lead:
        'Each one running in production for at least one client. We don\'t sell prototypes — we ship things that already work.',
      items: [
        { n: '/ 01', title: 'Custom', titleEm: 'ecommerce',
          body: 'Online store with catalog, cart, payment gateways (Mercado Pago, Stripe), e-invoicing and your own admin panel. No Shopify fees eating your margin.',
          tags: ['Mercado Pago', 'AFIP', 'Catalog', 'Multi-store'], mock: 'shop',
          stats: [{ n: '0%', l: 'commission per sale' }, { n: '<2s', l: 'mobile TTFB' }] },
        { n: '/ 02', title: 'Restaurant', titleEm: 'management',
          body: 'Kitchen orders, tables, takeaway, in-house delivery, stock control, daily reconciliation. Tablet on the floor, KDS at the grill.',
          tags: ['KDS', 'POS', 'Delivery', 'Stock', 'Cashbox'], mock: 'orders',
          stats: [{ n: '12s', l: 'avg ticket time' }, { n: '0', l: 'order mistakes' }] },
        { n: '/ 03', title: 'Gym', titleEm: '& wellness',
          body: 'Members, auto-debit subscriptions, QR access control, class booking with capacity, retention reports.',
          tags: ['Auto-debit', 'QR access', 'Classes', 'Retention'], mock: 'gym' },
        { n: '/ 04', title: 'E-ticketing', body: 'Ticket sales with offline-validable QR, sections, seat maps, door scanners and live event reports.', tags: ['Offline QR', 'Seat maps', 'Scanners'], mock: 'ticket' },
        { n: '/ 05', title: 'Queue management', body: 'For clinics, public offices, banks. TV screen, ticket dispenser, voice call-out, queue and service metrics.', tags: ['Multi-counter', 'TTS', 'Metrics'], mock: 'queue' },
        { n: '/ 06', title: 'Professional', titleEm: 'landings',
          body: 'For lawyers, accountants, doctors, architects. Custom design, serious forms, local SEO and sub-second load.',
          tags: ['Local SEO', 'A11y', '<1s'], mock: 'chart' },
      ],
    },
    process: {
      eyebrow: '02 — How we work',
      num: 'Chapter 02',
      title: 'Four weeks',
      titleEm: 'to production',
      lead:
        'No waterfall, no cardboard scrum. We iterate with you every week, show real progress and ship a running system, not a PDF.',
      steps: [
        { t: 'Discovery',   d: 'We visit you (yes, really). Map current flows, listen to the team, define the minimum viable scope.', dur: 'Week 01' },
        { t: 'Design',      d: 'Wireframes and clickable prototypes. Validated with real users before we touch a line of code.', dur: 'Week 02' },
        { t: 'Build',       d: '5-day sprints with Friday demos. You see the progress, give feedback, we adjust.', dur: 'Week 03–04' },
        { t: 'Launch',      d: 'Data migration, team training, hypercare week. Then: optional monthly support.', dur: 'Week 05' },
      ],
    },
    work: {
      eyebrow: '03 — Work',
      num: 'Chapter 03',
      title: 'Latest',
      titleEm: 'we shipped',
      lead: 'A sample. More under NDA — ask us for a private demo.',
      items: [
        { cat: 'Ecommerce',   t: 'La Posta — Valley Wines',         m: 'Store + monthly wine subscription. 480 active customers.', kind: 'shop' },
        { cat: 'Restaurants', t: 'Almacén del Sur — 3 locations',   m: 'Unified orders, stock and delivery. Ticket time ↓ 38%.', kind: 'orders' },
        { cat: 'Gyms',        t: 'Club Atlético San Pedro',         m: '1,200 members. Auto-debit, QR access, capped classes.', kind: 'gym' },
        { cat: 'E-ticketing', t: 'Pachamama Festival 2025',          m: '14,000 tickets sold. QR validation with zero internet at the gate.', kind: 'ticket' },
      ],
    },
    stack: {
      eyebrow: '04 — Stack',
      num: 'Chapter 04',
      title: 'What we use,',
      titleEm: 'no trade-show vibes',
      lead: 'We pick stable tools, not whatever ate Twitter last month. Everything here has been in our production for years.',
      items: [
        { n: 'TypeScript', c: 'Language' }, { n: 'React',     c: 'Frontend' },
        { n: 'Next.js',    c: 'Framework' },{ n: 'Node.js',   c: 'Backend' },
        { n: 'PostgreSQL', c: 'Database' }, { n: 'Redis',     c: 'Cache / queues' },
        { n: 'Prisma',     c: 'ORM' },      { n: 'Tailwind',  c: 'Styling' },
        { n: 'Mercado Pago', c: 'AR payments' }, { n: 'Stripe', c: 'USD payments' },
        { n: 'AFIP WS',    c: 'E-invoicing' }, { n: 'Cloudflare', c: 'Infra / CDN' },
      ],
    },
    quotes: {
      eyebrow: '05 — Reviews',
      num: 'Chapter 05',
      title: 'Don\'t take',
      titleEm: 'our word',
      lead: 'Trust the ones using it every day.',
      items: [
        { q: 'We went from Excel to a real system in five weeks. Members renew on their own via auto-debit and I stopped chasing late payments.',
          who: 'Mariano Quispe', role: 'Director, Club San Pedro', av: 'MQ' },
        { q: 'What I valued most: they came to the restaurant, understood how we worked and built something my waiter uses without any training.',
          who: 'Laura Mamaní', role: 'Owner, Almacén del Sur', av: 'LM' },
        { q: 'We validated 14,000 tickets in one night without internet on site. Unthinkable with our previous solution.',
          who: 'Diego Fernández', role: 'Producer, Pachamama Festival', av: 'DF' },
      ],
    },
    metrics: {
      items: [
        { n: '37', u: '', l: 'Projects shipped' },
        { n: '<5', u: 'w', l: 'Time to production' },
        { n: '99.9', u: '%', l: 'Uptime last 12m' },
        { n: '4', u: '', l: 'Active provinces' },
      ],
    },
    plans: {
      eyebrow: '· Plans',
      num: 'Chapter 03',
      title: 'Pick your plan,',
      titleEm: 'grow without a ceiling',
      lead: 'Every system comes in three sizes. Start with what you need today, scale when you need to. No eternal contracts: month-to-month, cancel any time.',
      payHd: 'Your customers pay with',
      payFoot: 'We enable each method at no extra cost. Fees apply per provider.',
      payMethods: [
        'Mercado Pago', 'MODO', 'Visa', 'Mastercard', 'American Express', 'Naranja X', 'Cabal', 'Bank transfer (CBU/CVU)', 'Cash (Pago Fácil/Rapipago)',
      ],
      tabs: [
        { id: 'ecommerce', n: '01', name: 'Ecommerce',     intro: 'Sell online without paying Shopify a toll.',         lead: 'Your own store with catalog, cart, payment gateway and AFIP e-invoicing. It\'s your platform — we don\'t take a cut of your sales.' },
        { id: 'ticket',    n: '02', name: 'E-ticketing',   intro: 'Sell tickets and validate QR offline at the door.',  lead: 'For festivals, theatres, shows and corporate events. Charge with Mercado Pago, assign seats, enter the venue without internet.' },
        { id: 'gastro',    n: '03', name: 'Restaurants',   intro: 'Waiter, kitchen, delivery and till — one system.',   lead: 'POS for tables and counter, KDS in the kitchen, in-house delivery, recipe-level stock and daily reconciliation.' },
        { id: 'gym',       n: '04', name: 'Gyms',          intro: 'Members, fees and QR access without losing sleep.',  lead: 'Auto-debit, QR access control, classes with capacity, retention metrics. For gyms, studios, pilates, crossfit.' },
        { id: 'queue',     n: '05', name: 'Queueing',      intro: 'Voice call-out, TV display and live metrics.',       lead: 'For clinics, public offices, banks and surgeries. Multi-counter, TTS, queue and service-time metrics.' },
        { id: 'landing',   n: '06', name: 'Pro landing',   intro: 'Your face online — no Wix templates.',                lead: 'Professional site for lawyers, accountants, doctors, architects. Custom design, serious forms, local SEO.' },
      ],
      monthly: '/mo',
      setup: 'Setup',
      featured: 'Most picked',
      footer: [
        { h: 'Accepted payment methods', p: 'Mercado Pago, MODO, every Argentine card (Visa, Mastercard, Amex, Naranja, Cabal) and CBU/CVU transfer. We enable whatever your business needs.' },
        { h: 'Your data, your code',     p: 'Repo, hosting and credentials in your name. If you stop working with us, we hand you the keys. No lock-in.' },
        { h: 'No invoice surprises',     p: 'Argentine peso prices. No commission per sale, no per-user charges, no hidden fees. Support included in every plan.' },
      ],
      software: {
        ecommerce: [
          { tier: 'Starter', tag: 'STR', sub: 'To start selling now', price: 89000, setup: 450000, feats: [
            ['Up to', '100 products'], ['', '1 store · 1 admin'], ['', 'Catalog + cart + checkout'],
            ['Pay:', 'Mercado Pago + transfer'], ['', 'AFIP e-invoicing'],
            ['', 'Domain + SSL + hosting included'], ['Support', 'email · 48 h'],
          ], muted: ['No recurring subscriptions', 'No native mobile app'] },
          { tier: 'Grow', tag: 'GRW', sub: 'To sell seriously', price: 159000, setup: 850000, featured: true, feats: [
            ['Up to', '1,000 products'], ['', '3 stores · 5 users'], ['', 'Everything in Starter, plus:'],
            ['Pay:', 'MP, MODO, Stripe, cards'], ['', 'Recurring / subscription orders'],
            ['', 'Coupons, discounts, gift cards'], ['', 'Andreani / OCA / Correo integration'],
            ['Support', 'WhatsApp · 24 h'],
          ], muted: ['No ERP / SAP integration'] },
          { tier: 'Pro', tag: 'PRO', sub: 'Operations at scale', price: 290000, setup: 'custom', feats: [
            ['', 'Unlimited products'], ['', 'Multi-store · unlimited users'], ['', 'Everything in Grow, plus:'],
            ['', 'Custom API + integrations'], ['', 'ERP / SAP / Tango / Bejerman'],
            ['', 'Multi-currency · multi-language'], ['', 'B2B portal + price lists'],
            ['', 'SLA 99.9% · staging environment'], ['Support', 'dedicated · 4 h'],
          ] },
        ],
        ticket: [
          { tier: 'Starter', tag: 'STR', sub: 'Your first online event', price: 'fee', priceNum: '4.5%', priceSuffix: 'per ticket sold', setup: 0, feats: [
            ['Up to', '500 tickets per event'], ['', '1 producer · 1 event at a time'], ['', 'Ticket types (general, vip, early)'],
            ['Pay:', 'Mercado Pago + transfer'], ['', 'Offline QR validation from phone'],
            ['', 'Live sales reports'], ['Support', 'email'],
          ], muted: ['No seat mapping', 'No physical scanners'] },
          { tier: 'Grow', tag: 'GRW', sub: 'Festivals and mid-size events', price: 'fee', priceNum: '3.5%', priceSuffix: 'per ticket sold', setup: 280000, featured: true, feats: [
            ['Up to', '5,000 tickets per event'], ['', 'Multiple simultaneous events'], ['', 'Everything in Starter, plus:'],
            ['', 'Seat / section mapping'], ['Pay:', 'MP + MODO + cards + debit'],
            ['', 'Up to 4 validation points'], ['', 'Optional physical scanners'],
            ['', 'WhatsApp with auto QR'], ['Support', 'WhatsApp · 24 h'],
          ] },
          { tier: 'Pro', tag: 'PRO', sub: 'Producers and big tours', price: 'fee', priceNum: '2.5%', priceSuffix: 'or monthly flat fee', setup: 'custom', feats: [
            ['', 'Unlimited tickets'], ['', 'Multi-event · multi-org'], ['', 'Everything in Grow, plus:'],
            ['', 'White-label with your brand'], ['', 'API + CRM integrations'],
            ['', 'Up to 20 validation points'], ['', 'Controlled resale + transfers'],
            ['', 'SLA 99.9% during the event'], ['Support', '24/7 on event night'],
          ] },
        ],
        gastro: [
          { tier: 'Starter', tag: 'STR', sub: 'One single location', price: 69000, setup: 380000, feats: [
            ['', '1 location · 5 devices'], ['', 'POS for tables and counter'], ['', 'Basic kitchen KDS'],
            ['', 'Stock per product'], ['Pay:', 'MP, cards, cash'],
            ['', 'Daily cash reconciliation'], ['Support', 'email · 48 h'],
          ], muted: ['No in-house delivery', 'No loyalty program'] },
          { tier: 'Grow', tag: 'GRW', sub: 'Up to 3 locations', price: 129000, setup: 680000, featured: true, feats: [
            ['', '3 locations · 15 devices'], ['', 'Everything in Starter, plus:'], ['', 'In-house delivery + riders'],
            ['', 'Recipe-level stock'], ['', 'Loyalty program'],
            ['Pay:', 'MP, MODO, cards, QR'], ['', 'Rappi / PedidosYa integration'],
            ['Support', 'WhatsApp · 24 h'],
          ] },
          { tier: 'Pro', tag: 'PRO', sub: 'Chains and franchises', price: 240000, setup: 'custom', feats: [
            ['', 'Unlimited locations'], ['', 'Everything in Grow, plus:'], ['', 'Multi-brand / multi-entity'],
            ['', 'BI: sales, waste, margin'], ['', 'API to plug your ERP'],
            ['', 'White-label customer app'], ['', 'SLA 99.9% in business hours'],
            ['Support', 'dedicated · 4 h'],
          ] },
        ],
        gym: [
          { tier: 'Starter', tag: 'STR', sub: 'Neighbourhood gym / studio', price: 59000, setup: 320000, feats: [
            ['Up to', '300 active members'], ['', '1 location'], ['', 'Fees + auto reminders'],
            ['Pay:', 'MP, transfer, cash'], ['', 'Manual access control'],
            ['', 'Digital QR card'], ['Support', 'email · 48 h'],
          ], muted: ['No auto-debit', 'No capped classes'] },
          { tier: 'Grow', tag: 'GRW', sub: 'Established gym', price: 119000, setup: 580000, featured: true, feats: [
            ['Up to', '1,500 active members'], ['', 'Up to 3 locations'], ['', 'Everything in Starter, plus:'],
            ['', 'Auto-debit MP / card'], ['', 'QR access control (turnstile)'],
            ['', 'Classes with capacity + waitlist'], ['', 'Retention + churn reports'],
            ['Support', 'WhatsApp · 24 h'],
          ] },
          { tier: 'Pro', tag: 'PRO', sub: 'Multi-site chain', price: 220000, setup: 'custom', feats: [
            ['', 'Unlimited members'], ['', 'Unlimited locations'], ['', 'Everything in Grow, plus:'],
            ['', 'Native mobile app (iOS + Android)'], ['', 'Bookings, assessments, training plans'],
            ['', 'Scale / cardio integration'], ['', 'Multi-site BI'],
            ['Support', 'dedicated · 4 h'],
          ] },
        ],
        queue: [
          { tier: 'Starter', tag: 'STR', sub: 'Single small office', price: 49000, setup: 240000, feats: [
            ['', '1 location · 3 counters'], ['', 'TV display + ticket dispenser'], ['', 'Audio call-out'],
            ['', 'Basic wait metrics'], ['', 'Printed or digital tickets'],
            ['Support', 'email · 48 h'],
          ], muted: ['No voice TTS', 'No advance booking'] },
          { tier: 'Grow', tag: 'GRW', sub: 'Multiple offices', price: 99000, setup: 480000, featured: true, feats: [
            ['', 'Up to 5 locations · 10 counters each'], ['', 'Everything in Starter, plus:'], ['', 'TTS: voice call-out per counter'],
            ['', 'Multiple queues / priorities'], ['', 'Online + WhatsApp pre-booking'],
            ['', 'Detailed metrics + dashboards'], ['Support', 'WhatsApp · 24 h'],
          ] },
          { tier: 'Pro', tag: 'PRO', sub: 'Banks / public offices', price: 180000, setup: 'custom', feats: [
            ['', 'Unlimited locations · unlimited counters'], ['', 'Everything in Grow, plus:'], ['', 'API + your-system integration'],
            ['', 'Post-service surveys'], ['', 'Complex routing rules'],
            ['', 'SLA 99.9% in business hours'], ['Support', 'dedicated · 4 h'],
          ] },
        ],
        landing: [
          { tier: 'Starter', tag: 'STR', sub: 'A site well-built', price: 19000, priceLead: 380000, setup: 0, feats: [
            ['One-off', '$ 380,000 + $ 19,000/mo hosting'], ['', '1 page · custom design'], ['', 'Up to 4 sections'],
            ['', 'Contact form · email'], ['', 'Local SEO + Google Business'],
            ['', 'Domain + SSL + hosting included'], ['Support', 'email · 1 change/mo'],
          ], muted: ['No blog / CMS', 'No multi-language'] },
          { tier: 'Grow', tag: 'GRW', sub: 'Your firm or surgery', price: 29000, priceLead: 680000, setup: 0, featured: true, feats: [
            ['One-off', '$ 680,000 + $ 29,000/mo hosting'], ['', '5 pages · custom design'], ['', 'Everything in Starter, plus:'],
            ['', 'Blog with CMS you edit'], ['', 'Built-in booking / agenda'],
            ['Pay:', 'MP for deposits / consultations'], ['', 'Multi-form + auto-replies'],
            ['Support', '4 changes/mo'],
          ] },
          { tier: 'Pro', tag: 'PRO', sub: 'Large studio or agency', price: 49000, priceLead: 1200000, setup: 0, feats: [
            ['One-off', '$ 1,200,000 + $ 49,000/mo hosting'], ['', 'Unlimited pages'], ['', 'Everything in Grow, plus:'],
            ['', 'Multi-language (ES/EN/PT)'], ['', 'CRM / HubSpot integration'],
            ['', 'A/B testing + analytics'], ['', 'Performance < 1 s · Lighthouse 95+'],
            ['Support', 'unlimited changes'],
          ] },
        ],
      },
      cta: 'Start with',
      ctaPro: 'Let\'s talk',
      currency: 'AR$',
    },
    faq: {
      eyebrow: '06 — Questions',
      num: 'Chapter 06',
      title: 'What we\'re',
      titleEm: 'always asked',
      items: [
        { q: 'How much does a project cost?', a: 'Depends on scope, but most start between USD 4K and USD 15K. We give a fixed quote after the discovery phase. No weird clauses.' },
        { q: 'Do you only work in the north?', a: 'No, but we know NOA business reality well. Clients in Buenos Aires, Mendoza, Córdoba and Asunción. In-person meetings work for Jujuy/Salta/Tucumán.' },
        { q: 'Who owns the code?', a: 'You do. Repo, credentials, hosting — all in your name. If you ever want to switch vendors, we hand you the keys.' },
        { q: 'Do you maintain it afterwards?', a: 'Yes, optional monthly plan from USD 350 with SLA. If you prefer another vendor or in-house team, we leave docs and transfer sessions.' },
        { q: 'Do you integrate with AFIP and Mercado Pago?', a: 'Yes — already built and battle-tested. E-invoicing, QR, discounts, auto-debit, the whole menu.' },
        { q: 'What if I need something not on the list?', a: 'We\'ve probably done it too. Write us what you need; if it\'s not our thing we recommend someone trustworthy.' },
      ],
    },
    contact: {
      eyebrow: '07 — Let\'s work together',
      num: 'Chapter 07',
      title: 'Tell us',
      titleEm: 'about it',
      lead: 'We reply in under 24 business hours. No sales funnels, no discovery agencies.',
      form: {
        name: 'Name',
        company: 'Company / project',
        email: 'Email',
        type: 'Project type',
        types: ['Ecommerce', 'Restaurants', 'Gyms', 'E-ticketing', 'Queueing', 'Pro landing', 'Other'],
        budget: 'Estimated budget',
        budgets: ['< USD 5K', 'USD 5–10K', 'USD 10–20K', '> USD 20K', 'Not sure yet'],
        msg: 'What do you need?',
        send: 'Send enquiry',
      },
      successTitle: 'Got it.',
      successBody: 'We reply within 24 business hours from hola@codigonorte.com.ar. If it\'s urgent, message us on WhatsApp.',
      aside: [
        { h: 'By email', body: <>Write to <a href="mailto:hola@codigonorte.com.ar">hola@codigonorte.com.ar</a></> },
        { h: 'On WhatsApp', body: <>9am–7pm GMT‑3. <a href="#">+54 388 415 0000</a></> },
        { h: 'In person', body: <>Belgrano 1024, San Salvador de Jujuy. Just call ahead so we can have coffee ready.</> },
      ],
    },
    footer: {
      cols: [
        { h: 'Products', links: ['Ecommerce', 'Restaurants', 'Gyms', 'E-ticketing', 'Queueing', 'Landings'] },
        { h: 'Company', links: ['About', 'Work', 'Blog', 'Privacy'] },
        { h: 'Contact', links: ['hola@codigonorte.com.ar', '+54 388 415 0000', 'WhatsApp', 'Instagram'] },
      ],
      base: '© 2025 Código Norte Soluciones — San Salvador de Jujuy, Argentina',
      baseRight: 'Last updated · v3.2.1',
      wordmark: 'codigo norte.',
    },
  },
};

window.COPY = COPY;
